// File: src/pages/tenants/kokitos/KokitosCase.jsx

import React from 'react';
import {
    Leaf, BarChart3, Thermometer, Droplet, CloudRainWind, Sun,
    ClipboardCheck, TrendingUp, MapPinned, Calculator, CheckSquare,
    CalendarClock, Tractor, Scissors, ShieldCheck
} from 'lucide-react';

const KokitosCase = () => {
    return (
        <div className="max-w-5xl mx-auto py-12 px-8 space-y-16">

            {/* Case Study Title */}
            <section className="text-center mb-8">
                <h1 className="text-3xl font-bold text-green-700">
                    Kokitos Case Study<br />
                    <span className="text-xl font-normal">First Quarter 2025, Jocotepec, Jalisco. Driscoll's Grower</span>
                </h1>
                <p className="mt-2 text-gray-500 italic">
                    The images and conclusions were generated by the Elathia agent.
                </p>
            </section>

            {/* Basis of the Powdery Mildew Risk Index (PMRI) */}
            <section>
                <h2 className="text-2xl font-semibold text-green-700 mb-4 flex items-center">
                    <BarChart3 className="mr-2 text-green-600" />Basis of the PMRI
                </h2>
                <p className="text-gray-700">
                    The Powdery Mildew Risk Index (PMRI) evaluates the probability of the development of the fungus <em>Podosphaera aphanis</em> according to identified optimal climatic conditions.
                </p>
                <div className="mt-6 bg-green-50 rounded-lg shadow p-6 flex items-center">
                    <BarChart3 className="text-green-600 mr-6" size={80} />
                    <ul className="list-disc text-gray-600">
                        <li><Thermometer className="inline-block mr-2 text-red-400"/> Optimal temperature close to 13°C.</li>
                        <li><Droplet className="inline-block mr-2 text-blue-400"/> Relative humidity approximately 67%.</li>
                        <li><CloudRainWind className="inline-block mr-2 text-indigo-400"/> Constant presence of surface moisture.</li>
                        <li><Sun className="inline-block mr-2 text-yellow-400"/> Mild day-night temperature variations.</li>
                    </ul>
                </div>
            </section>

            {/* Scientific References */}
            <section>
                <h2 className="text-2xl font-semibold text-green-700 mb-4 flex items-center">
                    <Leaf className="mr-2 text-green-600"/> Scientific References
                </h2>
                <p className="text-gray-700">
                    Ideal temperature (18°C-25°C), optimal relative humidity (60%-85%). Extreme conditions limit the activity of the fungus.
                </p>
                <div className="mt-6 bg-gray-50 rounded-lg shadow p-6 flex items-center">
                    <Thermometer className="text-red-500" size={60} />
                    <Droplet className="text-blue-500 ml-4" size={60} />
                    <p className="text-gray-600 italic ml-6">
                        Koppert (2024), IPM UCANR (2023), Editorial de Riego (2023).
                    </p>
                </div>
            </section>

            {/* Methodology and PMRI calculation */}
            <section>
                <h2 className="text-2xl font-semibold text-green-700 mb-4">
                    Methodology for Index Construction
                </h2>
                <p className="text-gray-700 mb-4">
                    The PMRI is a weighted average of temperature and humidity risks.
                </p>
                <div className="my-6 bg-gray-100 rounded-lg p-4 shadow font-mono text-center">
                    PMRI = (Temperature Risk + Humidity Risk) / 2
                </div>

                <table className="w-full shadow rounded-lg overflow-hidden">
                    <thead className="bg-gray-100">
                        <tr>
                            <th className="px-4 py-2">PMRI</th>
                            <th className="px-4 py-2">Risk Level</th>
                            <th className="px-4 py-2">Action</th>
                        </tr>
                    </thead>
                    <tbody className="text-gray-600">
                        <tr><td className="px-4 py-2">0-0.5</td><td>Low</td><td>Unfavorable conditions.</td></tr>
                        <tr className="bg-gray-50"><td className="px-4 py-2">0.5-1.5</td><td>Moderate</td><td>Monitoring and prevention.</td></tr>
                        <tr><td className="px-4 py-2">1.5-2.0</td><td>High</td><td>Immediate action.</td></tr>
                    </tbody>
                </table>
            </section>

            {/* Heatmaps */}
            <section>
                <h2 className="text-2xl font-semibold text-green-700 flex items-center mb-4">
                    <MapPinned className="mr-2 text-green-600" />Powdery Mildew Heatmap
                </h2>
                <img src="/assets/kokitos/mapa_calor_cenicilla.png" alt="Powdery Mildew Heatmap" className="rounded-lg shadow-md" />
            </section>

            <section>
                <h2 className="text-2xl font-semibold text-green-700 flex items-center mb-4">
                    <Droplet className="mr-2 text-blue-600" />Soil Moisture Heatmap
                </h2>
                <img src="/assets/kokitos/mapa_calor_humedad.png" alt="Soil Moisture Heatmap" className="rounded-lg shadow-md" />
            </section>

            {/* Hypothesis */}
            <section>
                <h2 className="text-2xl font-semibold text-green-700 flex items-center mb-4">
                    <TrendingUp className="mr-2 text-yellow-600"/> Risk Hypothesis
                </h2>
                <p className="text-gray-700">
                    Based on current data and the projected trend of the Powdery Mildew Risk Index (PMRI), a moderate increase in risk is expected in the next three weeks. This increase is driven by the combination of temperatures close to 13°C and relative humidity around 67%, conditions that, according to previous studies, favor the sporulation of the fungus 
 <em>Podosphaera aphanis</em>.
                </p>
            </section>

            {/* Recommendations */}
            <section>
                <h2 className="text-2xl font-semibold text-green-700 mb-4 flex items-center">
                    <ClipboardCheck className="mr-2 text-blue-600"/> Recommendations
                </h2>
                <ul className="text-gray-700">
                    <li><CheckSquare className="text-green-500"/> Rotation of Modes of Action.</li>
                    <li><CheckSquare className="text-green-500"/> Use of Biofungicides and Alternatives.</li>
                    <li><CheckSquare className="text-green-500"/> Preventive Applications in cool hours.</li>
                    <li><CheckSquare className="text-green-500"/> Preventive fungicides according to climate.</li>
                </ul>
            </section>

            {/* Weekly Activity Schedule for Crews */}
            <section>
                <h2 className="text-2xl font-semibold text-green-700 mb-4 flex items-center">
                    <CalendarClock className="mr-2 text-indigo-600" /> Weekly Activity Schedule for Crews
                </h2>
                <table className="w-full table-auto border-collapse shadow rounded-lg overflow-hidden">
                    <thead className="bg-gray-100">
                        <tr>
                            <th className="px-4 py-2 text-left">Day</th>
                            <th className="px-4 py-2 text-left">Activity</th>
                            <th className="px-4 py-2 text-left">Objective</th>
                            <th className="px-4 py-2 text-left">Responsible</th>
                        </tr>
                    </thead>
                    <tbody className="text-gray-600">
                        <tr>
                            <td className="px-4 py-2">Monday</td>
                            <td className="px-4 py-2"><Tractor className="inline mr-2 text-green-500" />Field Inspection</td>
                            <td className="px-4 py-2">Identify critical areas with initial symptoms of powdery mildew.</td>
                            <td className="px-4 py-2">Crew Member + Agricultural Supervisor</td>
                        </tr>
                        <tr className="bg-gray-50">
                            <td className="px-4 py-2">Tuesday</td>
                            <td className="px-4 py-2"><Droplet className="inline mr-2 text-red-400" />Fungicide Application (According to Schedule)</td>
                            <td className="px-4 py-2">Implement preventive control in high-risk areas.</td>
                            <td className="px-4 py-2">Application Crews</td>
                        </tr>
                        <tr>
                            <td className="px-4 py-2">Wednesday</td>
                            <td className="px-4 py-2"><Thermometer className="inline mr-2 text-red-400" />Humidity and Temperature Monitoring</td>
                            <td className="px-4 py-2">Evaluate environmental conditions that favor the disease.</td>
                            <td className="px-4 py-2">Crew Member + Field Technician</td>
                        </tr>
                        <tr className="bg-gray-50">
                            <td className="px-4 py-2">Thursday</td>
                            <td className="px-4 py-2"><Scissors className="inline mr-2 text-red-400" />Cleaning and Ventilation Pruning</td>
                            <td className="px-4 py-2">Remove excess foliage to improve air circulation.</td>
                            <td className="px-4 py-2">Maintenance Crews</td>
                        </tr>
                        <tr>
                            <td className="px-4 py-2">Friday</td>
                            <td className="px-4 py-2"><ShieldCheck className="inline mr-2 text-blue-400" />Second Inspection and Strategy Adjustments</td>
                            <td className="px-4 py-2">Verify the effectiveness of applied treatments.</td>
                            <td className="px-4 py-2">Crew Member + Supervisor</td>
                        </tr>
                        <tr className="bg-gray-50">
                            <td className="px-4 py-2">Saturday</td>
                            <td className="px-4 py-2"><Droplet className="inline mr-2 text-blue-500" />Irrigation and Soil Moisture Adjustment</td>
                            <td className="px-4 py-2">Prevent excessive moisture conditions.</td>
                            <td className="px-4 py-2">Irrigation Manager</td>
                        </tr>
                        <tr>
                            <td className="px-4 py-2">Sunday</td>
                            <td className="px-4 py-2"><ClipboardCheck className="inline mr-2 text-green-500" />Weekly Report and Planning</td>
                            <td className="px-4 py-2">Record progress and plan subsequent activities.</td>
                            <td className="px-4 py-2">Crew Member + Agricultural Supervisor</td>
                        </tr>
                    </tbody>
                </table>
            </section>

        </div>
    );
};

export default KokitosCase;